apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKERHUB/library-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: library-frontend
spec:
  selector:
    app: library-frontend
  ports:
    - port: 80
      targetPort: 80
